### PR TITLE
Correct csv file and add fillgaps function

### PR DESCRIPTION
**Pull request by juritaborri**

### CODE REVIEW

**Comment by juritaborri** [comment]
@aremazeilles  can you help me with these conflicts?

**Comment by aremazeilles** [comment]
I´ll have a look at it tomorrow afternoon if that is ok.

**Comment by aremazeilles** [comment]
If you look at here: https://github.com/aremazeilles/beat_routine/commits/Update_csv_and_function
It seems your last update is based on a branch which last commit is about the 4 of August.

If you look  at the master branch instead, https://github.com/aremazeilles/beat_routine/commits/master,
we see that some significant activity has occured since the 4 of August.

As already said, I already fixed the csv issue in the master branch.
Appart from the scientific notation, did you have anything more to change to the csv files?
If not I would rather try to branch from the current master, and insert in that branch only the changes you made on using the fillgaps function?

The operation you are asking otherwise is a bit cumbersome. 
I'll try to do what I suggest, and then tell you the outcomes of it.

**Comment by aremazeilles** [comment]
Check #40 If the CI process succeeds, I would merge the other, and discard this PR.

**Comment by aremazeilles** [comment]
I would suggest Closing this pull Request WITHOUT merging, and merge #40 instead.

**Pull request closed without merging**
