### PR TITLE
adding reference data, and adjust code

### PR DESCRIPTION
**Pull request by aremazeilles**

### CODE REVIEW

**Comment by aremazeilles** [comment]
Fix #2

**Comment by aremazeilles** [comment]
ping @juritaborri

**Comment by aremazeilles** [comment]
Looking at the output you generate.
All files should have an extension. I can work on that if you want. But the format of a PI output should be a yaml file, as indicated in the documentation: [here](https://github.com/aremazeilles/eurobench_documentation/blob/master/pi_spec.adoc#32-output-data) and [there](https://github.com/aremazeilles/eurobench_documentation/blob/master/template.adoc#41-output-type-field)

In the [octave example](https://github.com/eurobench/pi_octave_csic/blob/master/src/computePI.m#L76) you can see how we store a vector to a yaml file structure.

Matlab / Octave cells are not output format accepted. In your case it should be a matrix type, and then you should provide the matrix in such format:

```yaml
type: 'matrix'
value: [["label1", "label2", "label3", "label4", "label5", "label6"], [0.96867, 1.01667, 0.98843, 0.95168, 0.87936, 0.94576]]
```

If you indicate me (file, line) where you do such storage, I can help you with that.

**Comment by aremazeilles** [comment]
@alfonsotecnalia here we are in the case where storing labels with the vales would be needed. Should we define a specific output? It sounds like a labelled vector. We could think of something like:

```yaml
type: 'labelelled_vector'
label: ["label1", "label2", "label3", "label4", "label5", "label6"]
value: [0.96867, 1.01667, 0.98843, 0.95168, 0.87936, 0.94576]
```

What do you think?

**Comment by juritaborri** [comment]
> Looking at the output you generate.
> All files should have an extension. I can work on that if you want. But the format of a PI output should be a yaml file, as indicated in the documentation: [here](https://github.com/aremazeilles/eurobench_documentation/blob/master/pi_spec.adoc#32-output-data) and [there](https://github.com/aremazeilles/eurobench_documentation/blob/master/template.adoc#41-output-type-field)
> 
> In the [octave example](https://github.com/eurobench/pi_octave_csic/blob/master/src/computePI.m#L76) you can see how we store a vector to a yaml file structure.
> 
> Matlab / Octave cells are not output format accepted. In your case it should be a matrix type, and then you should provide the matrix in such format:
> 
> ```yaml
> type: 'matrix'
> value: [["label1", "label2", "label3", "label4", "label5", "label6"], [0.96867, 1.01667, 0.98843, 0.95168, 0.87936, 0.94576]]
> ```
> 
> If you indicate me (file, line) where you do such storage, I can help you with that.

Ok and sorry for that.
The creation of cell is prensent in:
- kinematic_routine_walking lines 89-92
-kinematic_routine_perturbation lines 60-62
-posturographic_routine_perturbation lines 6-48 and 72-74
-step_perturbation lines 37-41
-sinusoidal_perturbation lines 129-138

Let me know if you prefer adjusting code or I will performing it

**Review by juritaborri — APPROVED** [review]

**Comment by aremazeilles** [comment]
If you could do it, better. 
If you prefer me to do a first example, and then let you reproduce it, I would need the command to launch, with the input files, and associate it to the expected outcome files.

**Comment by juritaborri** [comment]
I will do it. Tomorrow I can work on it, today institutional meetings!

**Comment by aremazeilles** [comment]
Looking at the output PIs. file delta_theta,delta_theta in protocol6 is questionnable. First of all, I would avoid using comma in filename. Then it is particularly huge. 22Mo. 10 time bigger than the input file. Are you sure this corresponds to a PI output, ie a score than can be looked at by a person to compare several experiments?

**Comment by aremazeilles** [comment]
> I will do it. Tomorrow I can work on it, today institutional meetings!

Sure, no hurry

**Comment by juritaborri** [comment]
> Looking at the output PIs. file delta_theta,delta_theta in protocol6 is questionnable. First of all, I would avoid using comma in filename. Then it is particularly huge. 22Mo. 10 time bigger than the input file. Are you sure this corresponds to a PI output, ie a score than can be looked at by a person to compare several experiments?

There was a mistake in the processing. I will update the right file

**Comment by alfonsotecnalia** [comment]
> 
> 
> @alfonsotecnalia here we are in the case where storing labels with the vales would be needed. Should we define a specific output? It sounds like a labelled vector. We could think of something like:
> 
> ```yaml
> type: 'labelelled_vector'
> label: ["label1", "label2", "label3", "label4", "label5", "label6"]
> value: [0.96867, 1.01667, 0.98843, 0.95168, 0.87936, 0.94576]
> ```
> 
> What do you think?

I think that no new type is necessary. For me this is a matrix (or dataframe) and the first row contains labels. But maybe we need to introduce an optional (boolean) field "label" to indicate whether the matrix contains a row with labels. If no "label" field is provided, there is no such a row (all the rows are data). This field will serve to avoid not-allowed operations in intra/inter run aggregations (if it is specified to apply a mean to row 0 and it has the label field to True, then we can detect and inform that this operation is not possible or calculate the mean in the first data row).

**Comment by aremazeilles** [comment]
OK Alfonso so your suggestion is to stick to the current `type - value`  fields for the output file. And eventually add a tag for `label` (assuming if not present that no label is associated to it.

My only concern is to know how we should know the appropriate way to present (visually, on the front end) a given output. But maybe we should bring such discussion on other places?

**Comment by alfonsotecnalia** [comment]
I think so

**Comment by juritaborri** [comment]
> @alfonsotecnalia here we are in the case where storing labels with the vales would be needed. Should we define a specific output? It sounds like a labelled vector. We could think of something like:
> 
> ```yaml
> type: 'labelelled_vector'
> label: ["label1", "label2", "label3", "label4", "label5", "label6"]
> value: [0.96867, 1.01667, 0.98843, 0.95168, 0.87936, 0.94576]
> ```
> 
> What do you think?

**Comment by juritaborri** [comment]
> If you could do it, better.
> If you prefer me to do a first example, and then let you reproduce it, I would need the command to launch, with the input files, and associate it to the expected outcome files.

I have updload all the .yaml file.
Please let me know if are ok, specially regarding the one with labels

**Comment by aremazeilles** [comment]
I would propose to merge this, and then start working on adjusting the program. As far as I can see, you are not yet generating yaml file, which should be the next operations, associated to the main program entry point adjustment.

Do you agree?

**Comment by juritaborri** [comment]
> I would propose to merge this, and then start working on adjusting the program. As far as I can see, you are not yet generating yaml file, which should be the next operations, associated to the main program entry point adjustment.
> 
> Do you agree?

I do not know if there have been problems with the upload, but next week I have added the folder output with all the PIs in .yaml format, as well as modified the function by adding the code for saving PIs in .yaml. Can't you find it?

**Comment by aremazeilles** [comment]
I am in branch `input_output`, what I see here:

 ```console
anthony@PRT0962A ~/code/eurobench/beat_routine/output ‹input-output› 
╰─$ tree 
.
├── Protocol1
│   ├── CoV
│   ├── mROM
│   └── NoS
├── Protocol2
│   ├── CoV
│   ├── EA
│   ├── mROM
│   ├── NoS
│   ├── PL
│   ├── PL_AP
│   └── PL_ML
├── Protocol3
├── Protocol4
│   ├── EA
│   ├── PL
│   ├── PL_AP
│   └── PL_ML
├── Protocol5
│   ├── EA_p
│   ├── PL_p
│   └── ROM_p
├── Protocol6
│   ├── delta_theta
│   ├── EA_p
│   ├── OS
│   ├── PL_p
│   ├── ROM_p
│   └── theta_f
└── Protocol7
    ├── EA_p
    ├── G
    ├── phi
    └── PL_p

7 directories, 27 files
```

**Comment by aremazeilles** [comment]
Ok, you did it with the master branch apparently.
It would have been appropriate to push it the branch `input-output`. Do you know how you hsould have done it?

**Comment by aremazeilles** [comment]
Now I am not sure whether it makes sense to merge that branch. Could you check whether the changes in the .m files from that branch are still relevant? To do so, click on `Files Changes` above

**Comment by aremazeilles** [comment]
Calm down :)

**Comment by aremazeilles** [comment]
Can we have a quick phone call?

**Comment by aremazeilles** [comment]
I would rather have a quick phone call, this is getting messy. 
By the way you should be able to delete several files in a single commit. You are committing each file deletion (which generates me an email every time...)

**Comment by aremazeilles** [comment]
As we discussed @juritaborri , I would remove that branch, right ? The input-output information is already in master branch, correct?

**Comment by juritaborri** [comment]
Yes, right

**Pull request closed without merging**
