### PR TITLE
Simpler docker

### PR DESCRIPTION
**Pull request by aremazeilles**
Using apt to install octave dependencies

### CODE REVIEW

**Comment by aremazeilles** [comment]
ping @alfonsotecnalia , what do you think of these simplification?

**Comment by aremazeilles** [comment]
I mean, at the level of the docker file...

**Comment by alfonsotecnalia** [comment]
I like the idea to have the octave packages installed through apt-get but I do not know if it is better to put them in a separate script. The idea would be to have a basic octave image that could be taken as the basis for other images. However I do not know if we will have different different algorithms sharing the same version of octave

**Comment by aremazeilles** [comment]
Well, all package installation is still in a special file, install.sh, which could change from a repo to another. We just get rid of the 2 steps process, that is (1) download package, and (2) install package.

The only limitation I see is that this way we do not explicitly refer to a given tag of the package, so that changes of these package may affect the image when regenerated. Note that in that case the test check would detect any deviation.

I like how it simplifies the process although (no need of package_install.m). 
So unless you complain about it, I would rather go for that version, unless some repo explicitely require a given version of one of the packages.

**Comment by alfonsotecnalia** [comment]
> So unless you complain about it, I would rather go for that version, unless some repo explicitely require a given version of one of the packages.

No problem

**Pull request merged**
